version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scp -o "StrictHostKeyChecking no" -r ~/repo/* circleci@kzrv.tk:~/blog-back
              ssh circleci@kzrv.tk "cd blog-back && docker-compose up --build -d"
            fi
